[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "DoubleTensor"
version = "0.1.0"
dependencies = []

[tool.scikit-build]
cmake.minimum-version = "3.31"
